### ISSUE TITLE
Inject Cluster Name into ConfigMap in `cloud-provider-config` Helm Chart

### ISSUE THREAD

**Issue by afritzler** [onmetal/gardener-extension-provider-onmetal#231]
### Description

Following the latest changes in the `onmetal` Cloud Provider https://github.com/onmetal/cloud-provider-onmetal/pull/241, it is necessary to ensure that the cluster name is injected into the ConfigMap in the `cloud-provider-config` Helm Chart. 

### Proposed Solution

The `clusterName`, although not directly accessible from the `values.yaml` file, can be injected by the controlplane controller into the chart deployment. This way, the cluster name can be made available to the ConfigMap, allowing us to satisfy this requirement.

Here's a rough representation of how the injection might occur:

```yaml
# ... existing configMap data ...
metadata:
  name: my-configmap
  namespace: my-namespace
data:
  clusterName: {{ .Values.clusterName }}
# ... existing configMap data ...
```

In this case, the controlplane controller would need to ensure that the `clusterName` is appropriately set before the deployment of the chart.

### Additional context

Given the recent changes in the `onmetal` Cloud Provider, this feature has become essential for correct operation. It is necessary to implement this at the earliest to ensure a smooth transition for users and maintain the robustness of our service.

### Next Steps
- [ ] Confirm the feasibility and agreement on the proposed solution
- [ ] Update the controlplane controller to inject the clusterName into the chart deployment
- [ ] Test the implementation to ensure that the cluster name is correctly injected into the ConfigMap
- [ ] Update relevant documentation
